:- use_module(library(clpfd)).

/*Execute using:
 * swim(FNs, LNs, SS, CLs),
 * labeling([], FNs),
 * labeling([], LNs),
 * labeling([], SS),
 * labeling([], CLs).
*/

swim(FNs, LNs, SS, CLs):-
    FNs = [Sarah, Rachel, Melony, Amelia, Julia],
    FNs ins 1..5,
    all_different(FNs),
    LNs = [Sanford, Travers, James, West, Couch],
    LNs ins 1..5,
    all_different(LNs),
    SS = [S11, S12, S13, S21, S22],
    SS ins 1..5,
    all_different(SS),
    CLs = [Red, White, Blue, Yellow, Black],
    CLs ins 1..5,
    all_different(CLs),
    Rachel #= Travers,
    Rachel #\= Red,
    Rachel #= White + 1,
    White #= S11 #<==> C7,
    White #= S12 #<==> C8,
    White #= S13 #<==> C9,
    C7 + C8 + C9 #= 1,
    Melony #\= James,
    Melony #= 1,
    S11 #= 2 #<==> P12_1,
    S12 #= 2 #<==> P12_2,
    S13 #= 2 #<==> P12_3,
    P12_1 + P12_2 + P12_3 #= 1,
    Yellow #= S11 #<==> C1,
    Yellow #= S12 #<==> C2,
    Yellow #= S13 #<==> C3,
    C1 + C2 + C3 #= 1,
    Amelia #\= West,
    Amelia #= S11 #<==> C4,
    Amelia #= S12 #<==> C5,
    Amelia #= S13 #<==> C6,
    C4 + C5 + C6 #= 1,
    Rachel #= Couch + 1,
    Rachel #= Blue - 2,
    Julia #\= Couch,
    James #= S21 #<==> C10,
    James #= S22 #<==> C11,
    C10 + C11 #= 1,
    James #\= 5,
    James #\= Julia,
    James #\= Black,
    James #\= West,
    Julia #\= 5,
    Julia #\= Black,
    Julia #\= West,
    Black #= S21,
    Black #\= 5,
    Black #\= West,
    West #\= 5.
    
